name: notes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+1
  staggered_grid_view_flutter: ^0.0.4
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf

     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf

